# Generated by Django 4.0.3 on 2022-03-19 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_collection')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('title_search', models.CharField(blank=True, max_length=300, null=True)),
                ('image_second', models.ImageField(blank=True, null=True, upload_to='info_collection')),
                ('image_third', models.ImageField(blank=True, null=True, upload_to='info_collection')),
                ('full_content_first', models.TextField()),
                ('full_content_second', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'WeatherInfo',
            },
        ),
        migrations.CreateModel(
            name='WeatherNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('img_news', models.ImageField(blank=True, null=True, upload_to='news_collection')),
                ('img_news_first', models.ImageField(blank=True, null=True, upload_to='news_collection')),
                ('img_news_second', models.ImageField(blank=True, null=True, upload_to='news_collection')),
                ('full_content_first', models.TextField()),
                ('full_content_second', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'WeatherNews',
            },
        ),
    ]
